### PR TITLE
Feat/game UI redesign

### PR DESCRIPTION
**Pull request by adam-narozniak**
New design: (other buttons are not centered after a choice)

https://user-images.githubusercontent.com/51029327/170827159-35d7dd60-f6bd-4720-a2aa-8c2e873d7720.mov

### CODE REVIEW

**Review by panadax — CHANGES_REQUESTED** [review]
Look really nice!! Thanks for your work :) 👍 
One issue could be: don't forget to change the elements in the tests as well 
image

**Review by gaetschwartz — APPROVED** [review]
Are the images free to use ? LGHM otherwise

**Review by gaetschwartz — CHANGES_REQUESTED** [review]
Fix the tests though.

**Comment by adam-narozniak** [comment]
yes, free to use for non-commercial projects

**Review by gaetschwartz — APPROVED** [review]

**Review by panadax — APPROVED** [review]

**Pull request merged**
