### PR TITLE
Feat/bottom navigation

### PR DESCRIPTION
**Pull request by aladin6060**
I changed the navigation to a bottom navigation and change some of the colors according to figma. 
image

### CODE REVIEW

**Review by leonardopennino — APPROVED** [review]
LGTM! Also nice work readapting the tests! Appreciate your efforts! 👍

**Comment by panadax** [comment]
Well done! One small piece of advice is I think the color of the navigation bar and button seems to be not matched as shown in the screenshot, maybe we can change the color. Anyway, I like the overall design, and as Leonardo said it's really nice that you have implemented the corresponding test.

**Review by panadax — APPROVED** [review]

**Comment by aladin6060** [comment]
> Well done! One small piece of advice is I think the color of the navigation bar and button seems to be not matched as shown in the screenshot, maybe we can change the color. Anyway, I like the overall design, and as Leonardo said it's really nice that you have implemented the corresponding test.

H Thanks for the review! Do you mean that the color right at the top of the screen is whiter than the rest? If you mean that I am aware of it but could not find a fix sof far.

**Comment by aladin6060** [comment]
nevermind found a fix

**Pull request merged**
