### PR TITLE
Feat/leaderboard

### PR DESCRIPTION
**Pull request by panadax**
image

Hi guys,

As shown on the top, this is the prototype of LeaderBoard Page, please have a quick check! Thanks.

For further implementation with Firebase, I will discuss with you in the next sprint:

1. How can I get the user profile picture?
2. Basically, I need to add a field called "score" in User class, but I think many parts of the code should be changed like the test or somewhere else. And for online game service, we need add logic to add points to users.

### CODE REVIEW

**Comment by gaetschwartz** [comment]
> How can I get the user profile picture?
You can by accessing the `getUserProfilePictureUrl` of `Repository`. For now we don't have a proper way to do upload a profile piocture, so it doesn't really do much as there never is a profile picture.

> Basically, I need to add a field called "score" in User class, but I think many parts of the code should be changed like the test or somewhere else. And for online game service, we need add logic to add points to users.

For now. you can fetch and consume the score locally, kind of like you did in `FirebaseHelper`.

**Comment by panadax** [comment]
Thanks for your patient reply!  @gaetschwartz 

> You can by accessing the getUserProfilePictureUrl of Repository. For now we don't have a proper way to do upload a profile picture, so it doesn't really do much as there never is a profile picture.

Okay, I will refer to it and also I plan to add a code logic to show a default photo when the program could not fetch the photo.

> For now. you can fetch and consume the score locally, kind of like you did in FirebaseHelper.

Yes, I know that, but I think that should be different in implementing the leaderboard module. For stats module, we can calculate the score for the user logged in. However, for leaderboard module, I need to query **all** user's final overall points and sort the scores at the moment the user click the "leaderboard" button. So I think the overall point should be an attribute of User class.

**Comment by gaetschwartz** [comment]
The thing is it requires to track score and make sure to compute it correctly etc. Maybe I could write a firebase function that computes it and stores it like scores/{user_id}/ that you could then retrieve. To me it feels wrong to have it straight in the User object.

**Comment by panadax** [comment]
> The thing is it requires to track score and make sure to compute it correctly etc. Maybe I could write a firebase function that computes it and stores it like scores/{user_id}/ that you could then retrieve. To me it feels wrong to have it straight in the User object.

Your solution is great, I agree with it. The leaderboard is for online mode to rank for all users in our server so we just update the score for users when they finish an online game and the leaderboard module can retrieve the specific value to show on the user interface. 
A small question is I don't know what's the difference between your solution and adding an attribute in User class since one user have exact one "id" and have exact one "score". That's why I think it can be directly add to the User class.  Could you please  give more ideas about it? Thanks :)

**Comment by gaetschwartz** [comment]
There is not true correct or incorrect way here, I like separating the score here for a few reasons:
- The score changes every game, and I don't really like updating the user that often.
- As the user is fetched quite often, we want to keep it as light as possible.
- On server just as on client, updating the user could lead to some data loss if the user updates his name etc at the same time.

**Comment by panadax** [comment]
> There is not true correct or incorrect way here, I like separating the score here for a few reasons:
> 
> * The score changes every game, and I don't really like updating the user that often.
> * As the user is fetched quite often, we want to keep it as light as possible.
> * On server just as on client, updating the user could lead to some data loss if the user updates his name etc at the same time.

You convinced me 👍 I really appreciate your reply!!

**Comment by gaetschwartz** [comment]
Otherwise, I really like the UI, maybe the tiles could be a little smaller.

**Review by leonardopennino — APPROVED** [review]
Looks perfect to me, thank you for making the code modular and portable!

**Comment by panadax** [comment]
> Otherwise, I really like the UI, maybe the tiles could be a little smaller.

image

Yes, I noticed that. In fact, I intentionally make it a bit big since we can add more things in the tile of each player. Let's see the prototype with fake data.

In addition, under the user name, I left a blank for further implementation. For example, we can add a button here to send a friend request, or we add a text frame to show the user id or country, etc.

**Comment by panadax** [comment]
> Looks perfect to me, thank you for making the code modular and portable!

Thanks for your comment!! 😊

**Review by gaetschwartz — APPROVED** [review]

**Pull request merged**
