### PR TITLE
Feat/game page to fragment

### PR DESCRIPTION
**Pull request by adam-narozniak**
## Changes
* changed game action to fragment
* deleted email floating button from the right bottom corner (not useful in our application, present in all fragments)
## before:
image

## after:
image

image
(I don't know why the result 3:1 overlap with the username, rank; I'm leaving that for later to fix because I tried to do it fast thought couldn't)

### CODE REVIEW

**Comment by gaetschwartz** [comment]
I'm not a big fan of these icons, it looks unclear if we have to tap them, or if it is just illustrationnal. Maybe we could use emojis, or make them smaller ?

**Comment by adam-narozniak** [comment]
In my mind upper in the opponent, lower user. I was thinking that we can let a user choose a style later on. 

After you click the icon it changes the color, and the board and this is the screen when you want to play so I would assume that someone figures out that they have to click on sth, still I am up to making that clear. I wouldn't want to ship the app the way it looks, still, I would leave it, for now, and change the design later on because I don't find it crucial now. What do you think?

**Comment by gaetschwartz** [comment]
I didn't think it that way, let me do a little drawing.

**Comment by adam-narozniak** [comment]
@leonardopennino after the merge from the main my tests also crashed; I didn't think that might be the issue and was looking for a bug in my code with fragments since then and couldn't find it

**Comment by leonardopennino** [comment]
Yes @adam-narozniak the statistics fragment test is buggy. I am trying to fix it. The bug lies in the fact that the button to make the match_details appear is created at runtime hence the test has to wait for it to load or it fails. Working on a fix rn.

**Comment by adam-narozniak** [comment]
OK, I'm leaving it as it is, I've been working (trying to find the cause) on that and haven't finished the game simulation :((

**Review by panadax — APPROVED** [review]

**Pull request merged**
