### PR TITLE
Feat/link leadboard db

### PR DESCRIPTION
**Pull request by panadax**

### CODE REVIEW

**Comment by panadax** [comment]
Almost done except for the test of Leaderboard.

**Comment by panadax** [comment]
Here is the Firebase fetching for leaderboard module
image

The corresponding database design in Firebase
image

**Review by gaetschwartz — APPROVED** [review]
LGTM, great work !

**Review by adam-narozniak — COMMENTED** [review]
Hi, looks good. I just have one question. How are LeaderBodardInfo and TotalScore connected? I understand that TotalScore is needed because that's the form the data is stored on the Firebase and we need additional fetching of the data for LeaderBoardInfo, am I correct?

**Review by leonardopennino — APPROVED** [review]
Really great work! You correctly implemented my cache interface 👍

**Comment by panadax** [comment]
> Hi, looks good. I just have one question. How are LeaderBodardInfo and TotalScore connected? I understand that TotalScore is needed because that's the form the data is stored on the Firebase and we need additional fetching of the data for LeaderBoardInfo, am I correct?

Yes, you are right. In fact, the linking has been implemented in function "getLeaderBoard" in "FirebaseHelper.kt". First, I have fetch the score by "scores = repo.getLeaderBoardScore()" , iterate the "scores (class: List of TotalScore)" which contains the uid and uid's corresponding score and then "cast" to LeaderBoardInfo I want to return.  I hope it is clear :)

image

**Review by adam-narozniak — APPROVED** [review]
thanks for the explanation, everything is clear now

**Pull request merged**
