### PR TITLE
Feat/tic tac toe UI

### PR DESCRIPTION
**Pull request by panadax**
Basic Implementation of tic tac toe UI
image
image

### CODE REVIEW

**Comment by gaetschwartz** [comment]
I really like the design ! Did you make sure the assets were free to use ?

**Comment by gaetschwartz** [comment]
I really like the design 🤩, did you make sure the assets were free to use ?

**Comment by panadax** [comment]
> I really like the design 🤩, did you make sure the assets were free to use ?

Yes, I get icons and pics from a Chinese open-source repository website "https://www.iconfont.cn/?lang=en-us"!

**Review by gaetschwartz — APPROVED** [review]
LRGTM

**Review by aladin6060 — APPROVED** [review]
The interface looks really good!

**Pull request merged**
