### PR TITLE
Better reactivity

### PR DESCRIPTION
**Pull request by gaetschwartz**
- Add possibility to listen for the game state using `ChangeNotifier` and `StateNotifier`
- These two classes are custom.
The 2 classes to mainly check are [`ChangeNotifier`](https://github.com/SDP-Rock-Paper-Scissors/RockPaperScissors/blob/a61162ee85f586d549bdd35ec3484691ab5ed0a6/app/src/main/java/ch/epfl/sweng/rps/utils/ChangeNotifier.kt) and [`StateNotifier`](https://github.com/SDP-Rock-Paper-Scissors/RockPaperScissors/blob/a61162ee85f586d549bdd35ec3484691ab5ed0a6/app/src/main/java/ch/epfl/sweng/rps/utils/StateNotifier.kt).
~~- Rename `db` package to `logic`~~ **Revert to avoid lots of merge conflicts**

This allows now to listen for changes inside the `GameService` classes, using callbacks for Game objects changes and errors.

### CODE REVIEW

**Review by leonardopennino — APPROVED** [review]
LGTM!

**Review by panadax — APPROVED** [review]
almost LGTM! Could you please give some further explanation of the code in the "utils" directory you added since I don't really get what are "change notifier" and "state notifier" and when/where can we use them? Thanks in advance!

**Comment by gaetschwartz** [comment]
Sure, so essentially a ChangeNotifier is just a class that can have listeners, aka callbacks called when the notifyListeners is called. 
This allows to listen for a changes in a classes' property granted the class extends ChangeNotifier and calls notifyListeners when it does so.

StateNotifier is basically a ChangeNotifier holding a single value, so it can be useful when we only need to listen to changes for one single value.

You can check more usage on the GameService class.

**Comment by gaetschwartz** [comment]
fixes #87

**Pull request merged**
