### PR TITLE
Fix/refine stats page

### PR DESCRIPTION
**Pull request by panadax**
e999229c4d89ee91acba9a252440865

- Re-design the stats page for alignment with the whole app.  (If I win, the icon in the middle will be "smile", if lose, will be "sad".)
- Also, change some data structures for implementation.
- For the new requirement, change the selector (spinner element) with the game mode filter function (i.e. select t.t.t. or r.p.s )

Note, I changed something other than stats module only because I ran "code clean" function in Andriod Studio.

### CODE REVIEW

**Comment by gaetschwartz** [comment]
The text shouldn't be blck on blck, that's barely readable.

**Review by gaetschwartz — CHANGES_REQUESTED** [review]
The text shouldn't be blck on black, that's barely readable.

**Comment by panadax** [comment]
image


> The text shouldn't be blck on black, that's barely readable.

Thanks for your comment! Changed as below:)

image

**Review by gaetschwartz — APPROVED** [review]
Looks good to me, I really like this UI !

**Review by adam-narozniak — APPROVED** [review]
Looks good! If I understand correctly, the "1st player" username is 01/01/1970?

**Comment by panadax** [comment]
> Looks good! If I understand correctly, the "1st player" username is 01/01/1970?

No, I just put the match date there. it's obvious that it's current user to have a match and if I put username here, with the increasing match history, the same username information will be shown which I think it's a bit redundant.

**Pull request merged**
